### ISSUE TITLE
[Insight] Source code should not contain FIXME comments - in config/…/dev/easy_log_handler.yaml, line 6

### ISSUE THREAD

**Issue by keymener** [keymener/snowtricks#43]
**[in config/packages/dev/easy_log_handler.yaml, line 6](https://github.com/keymener/snowtricks/blob/7e0f97030fc43bcfe13e922cc3f63049792163cb/config/packages/dev/easy_log_handler.yaml#L6)**

> FIXME comments are left in the code when a bug has been noticed but not fixed. You should fix the bug and remove the comment.

```
services:
    EasyCorp\EasyLog\EasyLogHandler:
        public: false
        arguments: ['%kernel.logs_dir%/%kernel.environment%.log']

#// FIXME: How to add this configuration automatically without messing up with the monolog configuration?
#monolog:
#    handlers:
#        buffered:
#            type:     buffer
#            handler:  easylog
```

---------------------

_Posted from [SymfonyInsight](https://insight.symfony.com/projects/7d2ba0ba-9610-4212-8ccd-7f2d26096969/analyses/1)_
